/*THIS IS THE ANALYSIS OF THE FINANCIAL PERFORMANCE OF THE INC 5000 COMOANIES IN 2019*/

USE My_Biz
SELECT * FROM INC5TC

/*Dropping Unwanted Columns*/
ALTER TABLE INC5TC
DROP COLUMN PROFILE, URL 

SELECT * FROM INC5TC

/*Checking for null values */
SELECT * FROM INC5TC
WHERE RANK IS NULL 
AND COMPANY_NAME IS NULL
AND REVENUE IS NULL
AND GROWTH IS NULL
AND INDUSTRY IS NULL
AND WORKERS IS NULL
AND PREVIOUS_WORKERS IS NULL
AND FOUNDED IS NULL
AND YRS_ON_LIST IS NULL
AND METRO IS NULL
AND CITY IS NULL;

/*Capitalized the column Names using the MSSQL GUI*/
SELECT * FROM INC5TC

SELECT METRO, COUNT(*) AS NULLS_IN_METRO
FROM INC5TC
WHERE METRO IS NULL
GROUP BY METRO;

/*Data Cleaning by Moving into a new table without Null Values*/
SELECT * INTO DATA
FROM
(
SELECT * FROM INC5TC
WHERE RANK IS NOT NULL
AND COMPANY_NAME IS NOT NULL
AND REVENUE IS NOT NULL
AND GROWTH IS NOT NULL
AND INDUSTRY IS NOT NULL
AND WORKERS IS NOT NULL
AND PREVIOUS_WORKERS IS NOT NULL
AND FOUNDED IS NOT NULL
AND YRS_ON_LIST IS NOT NULL
AND METRO IS NOT NULL
AND CITY IS NOT NULL) AS DATA;


SELECT * FROM DATA

/*SELECTING TOP 10 BY RANK IN DESC*/
SELECT COMPANY_NAME, REVENUE, FOUNDED, INDUSTRY
FROM DATA
WHERE RANK <10
GROUP BY COMPANY_NAME, REVENUE, FOUNDED, INDUSTRY,RANK
ORDER BY RANK DESC

/*Revenue by Company without proper grouping by Industries*/
SELECT COMPANY_NAME, INDUSTRY, ROUND(AVG(REVENUE),2) AS COMPANY_AVERAGE_REVENUE
FROM DATA
GROUP BY COMPANY_NAME, REVENUE, INDUSTRY
ORDER BY REVENUE DESC

/*Revenue by Company Grouped by Industries*/
select Industry, Company_Name, count(*) Company_Nmber_Count, ROUND(avg(Revenue),2) as Avg_RevenuebyIndustry
from data
group by Industry, Company_Name, Revenue with rollup
ORDER BY Revenue DESC

/*Industries with highest representation*/
SELECT INDUSTRY, YRS_ON_LIST, COUNT(YRS_ON_LIST) AS COUNT_OF_REP
FROM DATA
GROUP BY INDUSTRY, YRS_ON_LIST
ORDER BY 3 DESC;

/*Industries with least representation*/
SELECT INDUSTRY, YRS_ON_LIST, COUNT(YRS_ON_LIST) AS COUNT_OF_REPRESENTATION
FROM DATA
GROUP BY INDUSTRY, YRS_ON_LIST
ORDER BY 3;

SELECT * FROM DATA

/*Grouping Revenue by State and City*/
select STATE, CITY, count(*) AS CITY_Nmber_Count, ROUND(avg(Revenue),2) as Avg_RevenuebyCITY
from data
group by STATE, CITY, Revenue with rollup
ORDER BY Revenue DESC

/*Finding Industry Growth Rates*/
SELECT INDUSTRY, GROWTH, ROUND(AVG(GROWTH),2) AS AVG_GROWTH_BY_INDUSTRY
FROM DATA
GROUP BY INDUSTRY, GROWTH
ORDER BY 3 DESC

/*Comapnies with the highest increase in staff*/
SELECT COMPANY_NAME,WORKERS, PREVIOUS_WORKERS,(SELECT(WORKERS-PREVIOUS_WORKERS)) AS NEW_HIRES
FROM DATA
GROUP BY COMPANY_NAME, WORKERS, PREVIOUS_WORKERS
ORDER BY 4 DESC
SELECT * FROM DATA

SELECT COMPANY_NAME,WORKERS, PREVIOUS_WORKERS, REVENUE,(SELECT(WORKERS-PREVIOUS_WORKERS)) AS NEW_HIRES
FROM DATA
GROUP BY COMPANY_NAME, WORKERS, PREVIOUS_WORKERS, REVENUE
ORDER BY 5

/*Revenue by State and City, Grouped by State and Revenue ordered in Desc*/
SELECT STATE, CITY, REVENUE, ROUND(SUM(REVENUE),2) AS Total_Revenue
FROM DATA
GROUP BY STATE, CITY, REVENUE WITH ROLLUP
ORDER BY 4 DESC

/*Classifying company based on growth levels*/
SELECT Company_Name,GROWTH,
CASE
WHEN GROWTH > 30000 THEN 'Best Performing' 
WHEN GROWTH < 25000 THEN 'Good Performance'
WHEN GROWTH < 15000 THEN 'Not Bad'
WHEN GROWTH < 10000 THEN 'Needs Improvement'
ELSE 'Investigate'
END AS Growth_Analysis_Label
FROM DATA

/*To find whether some companies had increased revenue after laying off some employees*/
SELECT COMPANY_NAME, ROUND(SUM(REVENUE),2) AS REVENUE,
CASE WHEN WORKERS - PREVIOUS_WORKERS <0 THEN 'Reduce'
ELSE 'Same'
END AS STATUS
FROM DATA
GROUP BY COMPANY_NAME, REVENUE, WORKERS, PREVIOUS_WORKERS
ORDER BY REVENUE DESC;

*/Still*/
SELECT COMPANY_NAME, 
(CASE
WHEN WORKERS < PREVIOUS_WORKERS THEN 'LESS'
WHEN WORKERS > PREVIOUS_WORKERS THEN 'MORE'
ELSE 'STABLE'
END) AS STAT
FROM DATA
GROUP BY COMPANY_NAME, WORKERS, PREVIOUS_WORKERS
ORDER BY STAT

/*Thanks for Reading*/